#ifndef _ONBOARD_HTML_H
#define _ONBOARD_HTML_H

static const char ONBOARD_HTML[] PROGMEM =
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"    <meta charset='utf-8'>\n"
"    <meta name='viewport' content='width=device-width,initial-scale=1'>\n"
"    <meta http-equiv='Content-Type' content='text/html; charset=utf-8'>\n"
"    <title>MimiClaw 设置</title>\n"
"    <style>\n"
"        * {\n"
"            box-sizing: border-box;\n"
"            margin: 0;\n"
"            padding: 0\n"
"        }\n"
"\n"
"        body {\n"
"            font-family: -apple-system, sans-serif;\n"
"            background: #f5f5f5;\n"
"            color: #333;\n"
"            padding: 16px;\n"
"            max-width: 480px;\n"
"            margin: 0 auto\n"
"        }\n"
"\n"
"        h1 {\n"
"            text-align: center;\n"
"            margin: 16px 0;\n"
"            font-size: 1.4em;\n"
"            color: #1a73e8\n"
"        }\n"
"\n"
"        .card {\n"
"            background: #fff;\n"
"            border-radius: 12px;\n"
"            margin: 12px 0;\n"
"            box-shadow: 0 1px 3px rgba(0, 0, 0, .12);\n"
"            overflow: hidden\n"
"        }\n"
"\n"
"        .card-hdr {\n"
"            display: flex;\n"
"            justify-content: space-between;\n"
"            align-items: center;\n"
"            padding: 14px 16px;\n"
"            cursor: pointer;\n"
"            user-select: none;\n"
"            font-weight: 600;\n"
"            font-size: .95em\n"
"        }\n"
"\n"
"        .card-hdr::after {\n"
"            content: '\\25BC';\n"
"            font-size: .7em;\n"
"            transition: transform .2s\n"
"        }\n"
"\n"
"        .card.collapsed .card-hdr::after {\n"
"            transform:rotate(-90deg)\n"
"        }\n"
"\n"
"        .card.collapsed .card-body {\n"
"            display: none\n"
"        }\n"
"\n"
"        .card-body {\n"
"            padding: 0 16px 16px\n"
"        }\n"
"\n"
"        label {\n"
"            display: block;\n"
"            margin: 10px 0 4px;\n"
"            font-size: .85em;\n"
"            color: #555\n"
"        }\n"
"\n"
"        input,\n"
"        select {\n"
"            width: 100%;\n"
"            padding: 10px 12px;\n"
"            border: 1px solid #ddd;\n"
"            border-radius: 8px;\n"
"            font-size: .95em;\n"
"            outline: none\n"
"        }\n"
"\n"
"        input:focus,\n"
"        select:focus {\n"
"            border-color: #1a73e8\n"
"        }\n"
"\n"
"        .btn {\n"
"            display: block;\n"
"            width: 100%;\n"
"            padding: 12px;\n"
"            border: none;\n"
"            border-radius: 8px;\n"
"            font-size: 1em;\n"
"            font-weight: 600;\n"
"            cursor: pointer;\n"
"            margin: 8px 0\n"
"        }\n"
"\n"
"        .btn-scan {\n"
"            background: #e8f0fe;\n"
"            color: #1a73e8\n"
"        }\n"
"\n"
"        .btn-save {\n"
"            background: #1a73e8;\n"
"            color: #fff;\n"
"            margin-top: 20px;\n"
"            font-size: 1.1em\n"
"        }\n"
"\n"
"        .btn:active {\n"
"            opacity: .8\n"
"        }\n"
"\n"
"        .ap-list {\n"
"            max-height: 200px;\n"
"            overflow-y: auto;\n"
"            border: 1px solid #ddd;\n"
"            border-radius: 8px;\n"
"            margin: 8px 0\n"
"        }\n"
"\n"
"        .ap-item {\n"
"            padding: 10px 12px;\n"
"            border-bottom: 1px solid #eee;\n"
"            cursor: pointer;\n"
"            display: flex;\n"
"            justify-content: space-between\n"
"        }\n"
"\n"
"        .ap-item:last-child {\n"
"            border-bottom: none\n"
"        }\n"
"\n"
"        .ap-item:active {\n"
"            background: #e8f0fe\n"
"        }\n"
"\n"
"        .ap-rssi {\n"
"            color: #888;\n"
"            font-size: .85em\n"
"        }\n"
"\n"
"        .ap-lock::before {\n"
"            content: '\\1F512';\n"
"            font-size: .75em;\n"
"            margin-right: 4px\n"
"        }\n"
"\n"
"        .status {\n"
"            text-align: center;\n"
"            padding: 20px;\n"
"            color: #1a73e8;\n"
"            font-size: 1.1em;\n"
"            display: none\n"
"        }\n"
"    </style>\n"
"</head>\n"
"\n"
"<body>\n"
"    <h1>MimiClaw 设置</h1>\n"
"    <p style='text-align:center;color:#666;font-size:.9em;margin-bottom:12px'>\n"
"        此门户网站仍可通过 192.168.4.1 访问，以获取后续更新。\n"
"    </p>\n"
"\n"
"    <!-- WiFi section (expanded by default) -->\n"
"    <div class='card' id='sec-wifi'>\n"
"        <div class='card-hdr' onclick='toggle(this)'>WiFi 配置</div>\n"
"        <div class='card-body'>\n"
"            <button class='btn btn-scan' onclick='scan()'>扫描 WiFi 网络</button>\n"
"            <div class='ap-list' id='ap-list' style='display:none'></div>\n"
"            <label>SSID</label>\n"
"            <input id='ssid' placeholder='WiFi network name'>\n"
"            <label>Password</label>\n"
"            <input id='password' type='password' placeholder='WiFi password'>\n"
"        </div>\n"
"    </div>\n"
"\n"
"    <!--- LLM section -->\n"
"    <div class='card collapsed' id='sec-llm'>\n"
"        <div class='card-hdr' onclick='toggle(this)'>LLM 配置</div>\n"
"        <div class='card-body'>\n"
"            <label>API Key</label>\n"
"            <input id='llm_api_key' type='password' placeholder='sk-...'>\n"
"            <label>模型</label>\n"
"            <input id='llm_model' placeholder='claude-opus-4-5' value='claude-opus-4-5'>\n"
"            <label>服务商</label>\n"
"            <select id='llm_provider'>\n"
"                <option value='anthropic'>Anthropic</option>\n"
"                <option value='openai'>OpenAI</option>\n"
"                <option value='deepseek'>Deepseek</option>\n"
"            </select>\n"
"        </div>\n"
"    </div>\n"
"\n"
"    <!-- Telegram section -->\n"
"    <div class='card collapsed' id='sec-tg'>\n"
"        <div class='card-hdr' onclick='toggle(this)'>Telegram Bot</div>\n"
"        <div class='card-body'>\n"
"            <label>Bot Token</label>\n"
"            <input id='tg_token' placeholder='123456:ABC-DEF...'>\n"
"        </div>\n"
"    </div>\n"
"\n"
"    <!-- Feishu section -->\n"
"    <div class='card collapsed' id='sec-feishu'>\n"
"        <div class='card-hdr' onclick='toggle(this)'>飞书 Bot</div>\n"
"        <div class='card-body'>\n"
"            <label>App ID</label>\n"
"            <input id='feishu_app_id' placeholder='cli_xxxx'>\n"
"            <label>App Secret</label>\n"
"            <input id='feishu_app_secret' type='password' placeholder='App Secret'>\n"
"        </div>\n"
"    </div>\n"
"\n"
"    <!-- Search section -->\n"
"    <div class='card collapsed' id='sec-search'>\n"
"        <div class='card-hdr' onclick='toggle(this)'>Web 搜索</div>\n"
"        <div class='card-body'>\n"
"            <label>服务商</label>\n"
"            <select id='search_provider'>\n"
"                <option value=''>None</option>\n"
"                <option value='brave'>Brave</option>\n"
"                <option value='tavily'>Tavily</option>\n"
"            </select>\n"
"            <label>Brave Search API Key</label>\n"
"            <input id='brave_key' type='password' placeholder='Brav...'>\n"
"            <label>Tavily API Key</label>\n"
"            <input id='tavily_key' type='password' placeholder='tvly-...'>\n"
"        </div>\n"
"    </div>\n"
"\n"
"    <!-- Proxy section -->\n"
"    <div class='card collapsed' id='sec-proxy'>\n"
"        <div class='card-hdr' onclick='toggle(this)'>网络代理</div>\n"
"        <div class='card-body'>\n"
"            <label>Host</label>\n"
"            <input id='proxy_host' placeholder='192.168.1.100'>\n"
"            <label>Port</label>\n"
"            <input id='proxy_port' type='number' placeholder='7890'>\n"
"            <label>Type</label>\n"
"            <select id='proxy_type'>\n"
"                <option value=''>None</option>\n"
"                <option value='http'>HTTP</option>\n"
"                <option value='socks5'>SOCKS5</option>\n"
"            </select>\n"
"        </div>\n"
"    </div>\n"
"\n"
"    <button class='btn btn-save' onclick='save()'>保存 &amp; 重启</button>\n"
"    <div class='status' id='status'>正在保存... 设备将重启.</div>\n"
"\n"
"    <script>\n"
"        function toggle(el) {\n"
"            el.parentElement.classList.toggle('collapsed')\n"
"        }\n"
"\n"
"        function loadConfig() {\n"
"            fetch('/config').then(r => r.json()).then(cfg => {\n"
"                Object.keys(cfg).forEach(k => {\n"
"                    var el = document.getElementById(k);\n"
"                    if (el && cfg[k] !== undefined && cfg[k] !== null) { el.value = cfg[k] }\n"
"                })\n"
"            }).catch(() => { })\n"
"        }\n"
"\n"
"        function scan() {\n"
"            var btn = event.target; btn.textContent = '扫描中...'; btn.disabled = true;\n"
"            fetch('/scan').then(r => r.json()).then(list => {\n"
"                var el = document.getElementById('ap-list'); el.style.display = 'block'; el.innerHTML = '';\n"
"                list.forEach(ap => {\n"
"                    var d = document.createElement('div'); d.className = 'ap-item';\n"
"                    d.innerHTML = '<span>' + (ap.auth ? '<span class=ap-lock></span>' : '') + ap.ssid + '</span><span class=ap-rssi>' + ap.rssi + ' dBm</span>';\n"
"                    d.onclick = function () { document.getElementById('ssid').value = ap.ssid };\n"
"                    el.appendChild(d)\n"
"                });\n"
"                btn.textContent = '扫描 WiFi 网络'; btn.disabled = false;\n"
"            }).catch(() => { btn.textContent = '扫描 WiFi 网络'; btn.disabled = false })\n"
"        }\n"
"\n"
"        function save() {\n"
"            var fields = ['ssid', 'password', 'llm_api_key', 'llm_model', 'llm_provider', 'tg_token',\n"
"                'feishu_app_id', 'feishu_app_secret', 'proxy_host', 'proxy_port', 'proxy_type', 'search_provider', 'tavily_key', 'brave_key'];\n"
"            var data = {};\n"
"            fields.forEach(f => { data[f] = document.getElementById(f).value.trim() });\n"
"            document.getElementById('status').style.display = 'block';\n"
"            fetch('/save', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) })\n"
"                .then(() => { document.getElementById('status').textContent = '已保存! 正在重启...'; })\n"
"                .catch(() => { document.getElementById('status').textContent = '出错. 请重试.'; })\n"
"        }\n"
"        loadConfig();\n"
"    </script>\n"
"</body>\n"
"</html>";

#endif